### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by jaredsburrows** [blipinsk/cortado#7]
Can we add TravisCI to build and run the tests?

**Comment by blipinsk** [comment]
I haven't tried Cortado with TravisCI yet... Give me few days, I'll try to investigate what can be done here.

**Comment by jaredsburrows** [comment]
I can submit a PR. Just let me know when you turn TravisCI on for this repository.

**Comment by blipinsk** [comment]
Done.

**Comment by blipinsk** [comment]
@jaredsburrows feel free to add the badge to README.md as well:

[![Build Status](https://travis-ci.org/blipinsk/cortado.svg?branch=master)](https://travis-ci.org/blipinsk/cortado)
`[![Build Status](https://travis-ci.org/blipinsk/cortado.svg?branch=master)](https://travis-ci.org/blipinsk/cortado)`

**Comment by jaredsburrows** [comment]
@blipinsk I forgot to add the badge to the README.md.

**Comment by blipinsk** [comment]
@jaredsburrows don't worry about that. I'll handle it 👍  Thanks for the PR!
